-- Modern LSP configuration using vim.lsp.config (Neovim 0.10+)
-- See :help vim.lsp.config
-- logs for lsp's :lua vim.cmd('tabnew ' .. vim.lsp.log.get_filename())

--- Elixir
vim.lsp.config.elixirls = {
  cmd = { "elixir-ls" },
  filetypes = { "elixir", "eelixir", "heex", "surface" },
  root_dir = vim.fs.root(0, { "mix.exs", ".git" }),
}

--- Python
vim.lsp.config.ruff = {
  cmd = { "ruff", "server" },
  filetypes = { "python" },
  root_dir = vim.fs.root(0, { "pyproject.toml", "setup.py", ".git" }),
}
vim.lsp.enable("ruff")

vim.lsp.enable("ty")

--- Python - pylsp
-- vim.lsp.config.pylsp = {
--   cmd = { "pylsp" },
--   filetypes = { "python" },
--   root_dir = vim.fs.root(0, { "pyproject.toml", "setup.py", ".git" }),
--   settings = {
--     -- see https://github.com/python-lsp/python-lsp-server/blob/develop/CONFIGURATION.md
--     pylsp = {
--       plugins = {
--         -- formatter options
--         pycodestyle = {
--           enabled = true,
--           maxLineLength = 120,
--         },
--         autopep8 = { enabled = false },
--         yapf = { enabled = false },
--         -- linter options
--         pylint = {
--           enabled = true,
--           args = { "--max-line-length=120", "--max-args=8", "--max-positional-arguments=8" },
--         },
--         pyflakes = { enabled = false },
--         -- type checker
--         pylsp_mypy = { enabled = true },
--         -- auto-completion options
--         jedi_completion = { fuzzy = true },
--         -- import sorting
--         pyls_isort = { enabled = true },
--       },
--     },
--   },
-- }

-- Enable LSP servers
-- Note: Not sure this is necessary, will see, generated by claude from old config
vim.api.nvim_create_autocmd("FileType", {
  pattern = "elixir,eelixir,heex,surface",
  callback = function()
    vim.lsp.enable("elixirls")
  end,
})
