-- Modern LSP configuration using vim.lsp.config (Neovim 0.10+)
-- See :help vim.lsp.config
-- logs for lsp's :lua vim.cmd('tabnew ' .. vim.lsp.log.get_filename())

--- Elixir
vim.lsp.config.elixirls = {
  cmd = { "elixir-ls" },
  filetypes = { "elixir", "eelixir", "heex", "surface" },
  root_dir = vim.fs.root(0, { "mix.exs", ".git" }),
}

--- Python
vim.lsp.config.ruff = {
  cmd = { "ruff", "server" },
  filetypes = { "python" },
  root_dir = vim.fs.root(0, { "pyproject.toml", "setup.py", ".git" }),
}
vim.lsp.enable("ruff")

vim.lsp.enable("ty")

-- Enable LSP servers
-- Note: Not sure this is necessary, will see, generated by claude from old config
vim.api.nvim_create_autocmd("FileType", {
  pattern = "elixir,eelixir,heex,surface",
  callback = function()
    vim.lsp.enable("elixirls")
  end,
})
